/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface BlackScholesInterface extends utils.Interface {
  functions: {
    "blackScholesCalc(uint256,uint256,uint256,uint256,uint256,bool)": FunctionFragment;
    "blackScholesCalcGreeks(uint256,uint256,uint256,uint256,uint256,bool)": FunctionFragment;
    "callOptionPrice(int256,int256,int256,int256,int256)": FunctionFragment;
    "callOptionPriceGreeks(int256,int256,int256,int256,int256)": FunctionFragment;
    "getDelta(uint256,uint256,uint256,uint256,uint256,bool)": FunctionFragment;
    "putOptionPrice(int256,int256,int256,int256,int256)": FunctionFragment;
    "putOptionPriceGreeks(int256,int256,int256,int256,int256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "blackScholesCalc",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "blackScholesCalcGreeks",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "callOptionPrice",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "callOptionPriceGreeks",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getDelta",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "putOptionPrice",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "putOptionPriceGreeks",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "blackScholesCalc",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "blackScholesCalcGreeks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "callOptionPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "callOptionPriceGreeks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getDelta", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "putOptionPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "putOptionPriceGreeks",
    data: BytesLike
  ): Result;

  events: {};
}

export interface BlackScholes extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: BlackScholesInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    blackScholesCalc(
      price: BigNumberish,
      strike: BigNumberish,
      expiration: BigNumberish,
      vol: BigNumberish,
      rfr: BigNumberish,
      isPut: boolean,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    blackScholesCalcGreeks(
      price: BigNumberish,
      strike: BigNumberish,
      expiration: BigNumberish,
      vol: BigNumberish,
      rfr: BigNumberish,
      isPut: boolean,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { quote: BigNumber; delta: BigNumber }>;

    callOptionPrice(
      d1: BigNumberish,
      d1Denominator: BigNumberish,
      price: BigNumberish,
      strike: BigNumberish,
      eToNegRT: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    callOptionPriceGreeks(
      d1: BigNumberish,
      d1Denominator: BigNumberish,
      price: BigNumberish,
      strike: BigNumberish,
      eToNegRT: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { quote: BigNumber; delta: BigNumber }>;

    getDelta(
      price: BigNumberish,
      strike: BigNumberish,
      expiration: BigNumberish,
      vol: BigNumberish,
      rfr: BigNumberish,
      isPut: boolean,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    putOptionPrice(
      d1: BigNumberish,
      d1Denominator: BigNumberish,
      price: BigNumberish,
      strike: BigNumberish,
      eToNegRT: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    putOptionPriceGreeks(
      d1: BigNumberish,
      d1Denominator: BigNumberish,
      price: BigNumberish,
      strike: BigNumberish,
      eToNegRT: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { quote: BigNumber; delta: BigNumber }>;
  };

  blackScholesCalc(
    price: BigNumberish,
    strike: BigNumberish,
    expiration: BigNumberish,
    vol: BigNumberish,
    rfr: BigNumberish,
    isPut: boolean,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  blackScholesCalcGreeks(
    price: BigNumberish,
    strike: BigNumberish,
    expiration: BigNumberish,
    vol: BigNumberish,
    rfr: BigNumberish,
    isPut: boolean,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber] & { quote: BigNumber; delta: BigNumber }>;

  callOptionPrice(
    d1: BigNumberish,
    d1Denominator: BigNumberish,
    price: BigNumberish,
    strike: BigNumberish,
    eToNegRT: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callOptionPriceGreeks(
    d1: BigNumberish,
    d1Denominator: BigNumberish,
    price: BigNumberish,
    strike: BigNumberish,
    eToNegRT: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber] & { quote: BigNumber; delta: BigNumber }>;

  getDelta(
    price: BigNumberish,
    strike: BigNumberish,
    expiration: BigNumberish,
    vol: BigNumberish,
    rfr: BigNumberish,
    isPut: boolean,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  putOptionPrice(
    d1: BigNumberish,
    d1Denominator: BigNumberish,
    price: BigNumberish,
    strike: BigNumberish,
    eToNegRT: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  putOptionPriceGreeks(
    d1: BigNumberish,
    d1Denominator: BigNumberish,
    price: BigNumberish,
    strike: BigNumberish,
    eToNegRT: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber] & { quote: BigNumber; delta: BigNumber }>;

  callStatic: {
    blackScholesCalc(
      price: BigNumberish,
      strike: BigNumberish,
      expiration: BigNumberish,
      vol: BigNumberish,
      rfr: BigNumberish,
      isPut: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    blackScholesCalcGreeks(
      price: BigNumberish,
      strike: BigNumberish,
      expiration: BigNumberish,
      vol: BigNumberish,
      rfr: BigNumberish,
      isPut: boolean,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { quote: BigNumber; delta: BigNumber }>;

    callOptionPrice(
      d1: BigNumberish,
      d1Denominator: BigNumberish,
      price: BigNumberish,
      strike: BigNumberish,
      eToNegRT: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    callOptionPriceGreeks(
      d1: BigNumberish,
      d1Denominator: BigNumberish,
      price: BigNumberish,
      strike: BigNumberish,
      eToNegRT: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { quote: BigNumber; delta: BigNumber }>;

    getDelta(
      price: BigNumberish,
      strike: BigNumberish,
      expiration: BigNumberish,
      vol: BigNumberish,
      rfr: BigNumberish,
      isPut: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    putOptionPrice(
      d1: BigNumberish,
      d1Denominator: BigNumberish,
      price: BigNumberish,
      strike: BigNumberish,
      eToNegRT: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    putOptionPriceGreeks(
      d1: BigNumberish,
      d1Denominator: BigNumberish,
      price: BigNumberish,
      strike: BigNumberish,
      eToNegRT: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { quote: BigNumber; delta: BigNumber }>;
  };

  filters: {};

  estimateGas: {
    blackScholesCalc(
      price: BigNumberish,
      strike: BigNumberish,
      expiration: BigNumberish,
      vol: BigNumberish,
      rfr: BigNumberish,
      isPut: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    blackScholesCalcGreeks(
      price: BigNumberish,
      strike: BigNumberish,
      expiration: BigNumberish,
      vol: BigNumberish,
      rfr: BigNumberish,
      isPut: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    callOptionPrice(
      d1: BigNumberish,
      d1Denominator: BigNumberish,
      price: BigNumberish,
      strike: BigNumberish,
      eToNegRT: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    callOptionPriceGreeks(
      d1: BigNumberish,
      d1Denominator: BigNumberish,
      price: BigNumberish,
      strike: BigNumberish,
      eToNegRT: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getDelta(
      price: BigNumberish,
      strike: BigNumberish,
      expiration: BigNumberish,
      vol: BigNumberish,
      rfr: BigNumberish,
      isPut: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    putOptionPrice(
      d1: BigNumberish,
      d1Denominator: BigNumberish,
      price: BigNumberish,
      strike: BigNumberish,
      eToNegRT: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    putOptionPriceGreeks(
      d1: BigNumberish,
      d1Denominator: BigNumberish,
      price: BigNumberish,
      strike: BigNumberish,
      eToNegRT: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    blackScholesCalc(
      price: BigNumberish,
      strike: BigNumberish,
      expiration: BigNumberish,
      vol: BigNumberish,
      rfr: BigNumberish,
      isPut: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    blackScholesCalcGreeks(
      price: BigNumberish,
      strike: BigNumberish,
      expiration: BigNumberish,
      vol: BigNumberish,
      rfr: BigNumberish,
      isPut: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    callOptionPrice(
      d1: BigNumberish,
      d1Denominator: BigNumberish,
      price: BigNumberish,
      strike: BigNumberish,
      eToNegRT: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    callOptionPriceGreeks(
      d1: BigNumberish,
      d1Denominator: BigNumberish,
      price: BigNumberish,
      strike: BigNumberish,
      eToNegRT: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getDelta(
      price: BigNumberish,
      strike: BigNumberish,
      expiration: BigNumberish,
      vol: BigNumberish,
      rfr: BigNumberish,
      isPut: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    putOptionPrice(
      d1: BigNumberish,
      d1Denominator: BigNumberish,
      price: BigNumberish,
      strike: BigNumberish,
      eToNegRT: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    putOptionPriceGreeks(
      d1: BigNumberish,
      d1Denominator: BigNumberish,
      price: BigNumberish,
      strike: BigNumberish,
      eToNegRT: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
