export const DISCORD_LINK = 'https://discord.gg/62846YV7NY'
export const GITHUB_LINK = 'https://github.com/rysk-finance'
export const TWITTER_LINK = 'https://twitter.com/ryskfinance'
export const DOCS_LINK = 'https://docs.rysk.finance/'
export const BLOG_LINK = 'https://medium.com/@rysk-finance'
