export enum QueriesEnum {
  DASHBOARD_USER_POSITIONS = "DASHBOARD_USER_POSITIONS",
  OPTIONS_CHAIN_EXPIRY_DATES = "OPTIONS_CHAIN_EXPIRY_DATES",
  ORACLE_ASSETS = "ORACLE_ASSETS",
  USER_BALANCE_DATA = "USER_BALANCE_DATA",
  USER_EPOCH_PNL = "USER_EPOCH_PNL",
  USER_VAULT = "USER_VAULT",
  USER_VAULT_COUNT = "USER_VAULT_COUNT",
  VAULT_PERFORMANCE = "VAULT_PERFORMANCE",
  VAULT_TRADE = "VAULT_TRADES",
}
