export enum QueriesEnum {
  DASHBOARD_USER_POSITIONS = "DASHBOARD_USER_POSITIONS",
  INITIAL_DATA = "INITIAL_DATA",
  ORACLE_ASSETS = "ORACLE_ASSETS",
  USER_EPOCH_PNL = "USER_EPOCH_PNL",
  USER_VAULT = "USER_VAULT",
  USER_VAULT_COUNT = "USER_VAULT_COUNT",
  VAULT_PERFORMANCE = "VAULT_PERFORMANCE",
  VAULT_TRADE = "VAULT_TRADES",
}
