/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ArbSys, ArbSysInterface } from "../ArbSys";

const _abi = [
  {
    inputs: [],
    name: "arbBlockNumber",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ArbSys__factory {
  static readonly abi = _abi;
  static createInterface(): ArbSysInterface {
    return new utils.Interface(_abi) as ArbSysInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): ArbSys {
    return new Contract(address, _abi, signerOrProvider) as ArbSys;
  }
}
