/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IClearingHouseOwnerActions,
  IClearingHouseOwnerActionsInterface,
} from "../IClearingHouseOwnerActions";

const _abi = [
  {
    inputs: [
      {
        internalType: "contract IERC20",
        name: "cToken",
        type: "address",
      },
      {
        components: [
          {
            internalType: "contract IOracle",
            name: "oracle",
            type: "address",
          },
          {
            internalType: "uint32",
            name: "twapDuration",
            type: "uint32",
          },
          {
            internalType: "bool",
            name: "isAllowedForDeposit",
            type: "bool",
          },
        ],
        internalType: "struct IClearingHouseStructures.CollateralSettings",
        name: "collateralSettings",
        type: "tuple",
      },
    ],
    name: "updateCollateralSettings",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint32",
        name: "poolId",
        type: "uint32",
      },
      {
        components: [
          {
            internalType: "uint16",
            name: "initialMarginRatioBps",
            type: "uint16",
          },
          {
            internalType: "uint16",
            name: "maintainanceMarginRatioBps",
            type: "uint16",
          },
          {
            internalType: "uint16",
            name: "maxVirtualPriceDeviationRatioBps",
            type: "uint16",
          },
          {
            internalType: "uint32",
            name: "twapDuration",
            type: "uint32",
          },
          {
            internalType: "bool",
            name: "isAllowedForTrade",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "isCrossMargined",
            type: "bool",
          },
          {
            internalType: "contract IOracle",
            name: "oracle",
            type: "address",
          },
        ],
        internalType: "struct IClearingHouseStructures.PoolSettings",
        name: "newSettings",
        type: "tuple",
      },
    ],
    name: "updatePoolSettings",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint16",
            name: "rangeLiquidationFeeFraction",
            type: "uint16",
          },
          {
            internalType: "uint16",
            name: "tokenLiquidationFeeFraction",
            type: "uint16",
          },
          {
            internalType: "uint16",
            name: "closeFactorMMThresholdBps",
            type: "uint16",
          },
          {
            internalType: "uint16",
            name: "partialLiquidationCloseFactorBps",
            type: "uint16",
          },
          {
            internalType: "uint16",
            name: "insuranceFundFeeShareBps",
            type: "uint16",
          },
          {
            internalType: "uint16",
            name: "liquidationSlippageSqrtToleranceBps",
            type: "uint16",
          },
          {
            internalType: "uint64",
            name: "maxRangeLiquidationFees",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "minNotionalLiquidatable",
            type: "uint64",
          },
        ],
        internalType: "struct IClearingHouseStructures.LiquidationParams",
        name: "liquidationParams",
        type: "tuple",
      },
      {
        internalType: "uint256",
        name: "removeLimitOrderFee",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "minimumOrderNotional",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "minRequiredMargin",
        type: "uint256",
      },
    ],
    name: "updateProtocolSettings",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "numberOfPoolsToUpdateInThisTx",
        type: "uint256",
      },
    ],
    name: "withdrawProtocolFee",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IClearingHouseOwnerActions__factory {
  static readonly abi = _abi;
  static createInterface(): IClearingHouseOwnerActionsInterface {
    return new utils.Interface(_abi) as IClearingHouseOwnerActionsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IClearingHouseOwnerActions {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IClearingHouseOwnerActions;
  }
}
